### ISSUE TITLE
Rigid registration for non-square images

### ISSUE THREAD

**Issue by amirid** [airlab-unibas/airlab#8]
Hi,

In the following function, how do you handle the non-square images? I think the magnitude of  displacement vectors should be tuned according to the ratio of image length and width.

https://github.com/airlab-unibas/airlab/blob/051f9364e0bfb9974ebbaef271765183f25c08f6/airlab/transformation/pairwise.py#L89-L105

**Comment by RobinSandkuehler** [comment]
Hi, 
we handle non-square images by creating an image grid (-1, -1) -- (1, 1) for the image. If the image is not a square image, the delta of the grid is different for the width and the height. This leads to an implicit scaling for the height and the width. I hope this helps, otherwise please let me know.
